config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  unauthenticated do
    root :to => 'sessions#new'
  end
  
  authenticated do
    root :to => 'records#index'
  end

  # root 'records#index'

  resources :records
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
    belongs_to :user

    def self.sorted_desc
        order(date: :desc, time: :desc)
        # sort_by{ |t| [t.date, t.time] }
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :records
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # protect_from_forgery with: :exception
    # before_action :require_log_in

    # helper_method :current_user
    # helper_method :logged_in?

    # def logged_in?
    #     !!current_user
    # end


    # private

    # def require_log_in
    #     redirect_to root_path unless logged_in?
    # end

    # def current_user
    #     @current_user ||= User.find_or_create_by(id: session[:user_id]) if session[:user_id]
    # end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
    before_action :set_record, only: [:show, :edit, :update, :destroy]
    include RecordsHelper

    def index
        @records = Record.all.sorted_desc
    end


    def show
    end


    def new
        @record = Record.new
    end


    def create
        @record = Record.create(record_params)
        if @record.save!
            redirect_to records_path
        else
            render :new
        end
    end


    def edit
    end


    def update
        if @record.update(record_params)
            redirect_to records_path
        else
            render :edit
        end
    end


    def destroy
        @record.destroy
        redirect_to records_path
    end



    private

    def record_params
        params.require(:record).permit(:user_id, :date, :time, :reading, :dose)
    end

    
    def set_record
        @record = Record.find_by(id: params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BsTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    
    <nav class="navbar navbar-expand-md navbar-light" style="background-color: #92cbf5;">
      <div class="container">
        <a class="navbar-brand font-weight-light" href="/">Blood Sugar Tracker</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link font-weight-lighter" href="/records">Readings</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link font-weight-lighter" href="/records/new">New Reading</a>
            </li>
          </ul>
          <span class="navbar-text">
            <%= link_to 'log out', destroy_user_session_path, :method => :delete %>
          </span>
        </div>
      </div>
    </nav>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <br/>

    <div class="container font-weight-lighter">
      <%= yield %>
    </div>

    <footer>
      <div class="container font-weight-lighter text-dark-50">
        <br/>
        <em>RyanEvns <%= Time.now.year %></em>
      </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

  </body>
</html>

app/views/records/edit.html.erb
<div class="row">
    <div class="col-sm">
        <h2>Edit Reading</h2>
    </div>
</div>
<br/>

<%= form_for @record do |f| %>
    <form>

        <%= f.hidden_field :user_id, value: current_user.id %>
        <div class="form-group row">        
            <label for="date" class="col-sm-1 col-form-label">Date</label>
            <div class="col-sm-1"">
                <%= f.date_field :date, autofocus: true, :required => true %>
            </div>
        </div>

        <div class="form-group row">
            <label for="time" class="col-sm-1 col-form-label">Time</label>
            <div class="col-sm-1">
                <%= f.time_field :time, :required => true %>
            </div>
        </div>

        <div class="form-group row">
            <label for="reading" class="col-sm-1 col-form-label">Reading</label>
            <div class="col-sm-1">
                <%= f.number_field :reading, :required => true %>
            </div>
        </div>
            
        <div class="form-group row">
            <label for="dose" class="col-sm-1 col-form-label">Dose</label>
            <div class="col-sm-1">
                <%= f.text_field :dose, :value => 'None', :required => true %>
            </div>
        </div>

        <br/>
        
        <div class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn-sm btn-outline-success font-weight-light">Update</button>
            </div>
        </div>
    </form>
<% end %>

app/views/records/index.html.erb
<div class="row">
  <h2>Records Index Page</h2>
</div>
<br>
<div class="row align-items-center">
  <% @records.each do |record| %>
      <div class="col-sm-3">
          <br>
          <strong><%= record.date.strftime('%m-%d') %></strong>
          <br>
          <strong><%= record.time.strftime('%I:%M %p') %></strong>
          <br>
          Reading:
          <%= record.reading %>
          <br>
          Dose:
          <%= record.dose %>
          <br>
          <%= link_to "Edit", edit_record_path(record) %>
      </div>
    <br>
  <% end %>
</div>

app/views/records/new.html.erb
<div class="row">
    <div class="col-sm">
        <h2>New Reading</h2>
    </div>
</div>
<br/>

<%= form_for @record do |f| %>
    <form>

        <%= f.hidden_field :user_id, value: current_user.id %>
        <div class="form-group row">        
            <label for="date" class="col-sm-1 col-form-label">Date</label>
            <div class="col-sm-1"">
                <%= f.date_field :date, autofocus: true, :required => true %>
            </div>
        </div>

        <div class="form-group row">
            <label for="time" class="col-sm-1 col-form-label">Time</label>
            <div class="col-sm-1">
                <%= f.time_field :time, :required => true %>
            </div>
        </div>

        <div class="form-group row">
            <label for="reading" class="col-sm-1 col-form-label">Reading</label>
            <div class="col-sm-1">
                <%= f.number_field :reading, :required => true %>
            </div>
        </div>
            
        <div class="form-group row">
            <label for="dose" class="col-sm-1 col-form-label">Dose</label>
            <div class="col-sm-1">
                <%= f.text_field :dose, :value => 'None', :required => true %>
            </div>
        </div>

        <br/>
        
        <div class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn-sm btn-outline-success font-weight-light">Add Reading</button>
            </div>
        </div>
    </form>
<% end %>